### ISSUE TITLE
Cannot find module 'noia-node'

### ISSUE THREAD

**Issue by rodrigosobrero** [noia-network/noia-node-terminal#7]
I'm getting this error when I run `npm start`:

```
Error: Cannot find module 'noia-node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/noia-node-terminal/index.js:8:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

I also tried `npm install noia-node` but still not working.

**Comment by rodrigosobrero** [comment]
I did `git clone https://github.com/noia-network/noia-node-terminal.git`.

**Comment by litsph** [comment]
> It was the npm version. Updated to the last version (6.2.0) and now it's working.

whats the command for updating the npm?
